services:
  - type: web
    name: geo-sparkle-react-06277
    env: docker
    branch: main
    region: oregon
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: free
    instanceType: starter
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_GOOGLE_MAPS_API_KEY
        value: ''
      - key: NASA_PROXY_URL
        value: ''
