name: Docker Build Smoke Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: geo-sparkle:ci

      - name: List docker images
        run: |
          docker images --format "{{.Repository}}:{{.Tag}} {{.Size}}" | grep -E "geo-sparkle:ci" || docker images

      - name: Run container in background
        run: |
          docker run --rm -d -p 3000:3000 --name geo-sparkle-ci geo-sparkle:ci || true

      - name: Wait for server
        run: |
          for i in {1..20}; do
            if curl -sS http://localhost:3000 >/dev/null 2>&1; then
              echo "server up"; exit 0
            fi
            echo "waiting..."; sleep 2
          done
          echo "server did not respond"; exit 1

      - name: Stop container
        if: always()
        run: |
          docker ps -a --filter "name=geo-sparkle-ci" --format "{{.ID}}" | xargs -r docker stop
