name: Docker Build Smoke Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: geo-sparkle:ci

      - name: List docker images
        run: |
          docker images --format "{{.Repository}}:{{.Tag}} {{.Size}}" | grep -E "geo-sparkle:ci" || docker images
